V1.1 public review doc
biometricITC/Public-Review pull request #1
Opened 2021-06-29 17:10 UTC by woodbe

The overview document for the public review 1 period.

2021-06-30 20:03 UTC, gregott commented on v1.1 Review/Public_review_1.1.adoc
> +It is important to note that this information is needed for testing that the samples provided to the biometric system have the information needed to build a template and then to verify a new sample t
I am not sure what is meant by the phrase "and then to verify a new sample to the template."  Are you saying that templates built from new biometric samples have enough information to build a template that can then be used for a match determination to an enrolled template?

2021-06-30 20:11 UTC, woodbe commented on v1.1 Review/Public_review_1.1.adoc
> +It is important to note that this information is needed for testing that the samples provided to the biometric system have the information needed to build a template and then to verify a new sample t
Something along those lines, like what Greg F was pointing out that the focus here is on how to determine quality to be able to create low quality samples. I'm happy to change the wording here if you have a suggestion (I was a little at a loss in better phrasing).

2021-06-30 20:27 UTC, gregott commented on v1.1 Review/Public_review_1.1.adoc
> +It is important to note that this information is needed for testing that the samples provided to the biometric system have the information needed to build a template and then to verify a new sample t
How about something along these lines:  It is important to note that this information is needed for testing that the samples provided to the biometric system have sufficient information needed to build templates which will result in the desired performance, i.e. acceptable error rates.  So the focus is on how to create poor samples and how to ensure they are discarded from use.

2021-06-30 20:33 UTC, woodbe commented
@gregott I just posted that change. Thank you for the comment.

2021-07-01 05:09 UTC, n-kai requested changes
Could you correct the following errors?

- "Link" in Table 1. Review Documents are not correct
- Delete "cYEL" in the 2nd box of first row in the figure under Document Release Process

2021-07-01 10:27 UTC, woodbe commented
@n-kai thank you for the review. The links will work once I publish everything, those are where I will put the docs (but I hadn't generated anything or uploaded them yet).

As for the cYEL, that is a code in the ditaa that will make that box yellow once I product the final output. When we do the next review period (so the next version of this document for the next review period), I will move that cYEL into the next review period box so that one will be yellow, to show which step we are on.

2021-07-01 10:36 UTC, merged